"use client";

import { useState, useEffect } from "react";
import { sentences } from "../data/sentences";
import { useStore } from "../store/useStore";
import Flashcard from "../components/Flashcard";
import { ThemeToggle } from "../components/ThemeToggle";
import { BookOpen, AlertTriangle } from "lucide-react";

export default function Home() {
  const { getNextSentenceId, missedWords, selectedLevel, setSelectedLevel, completedSentences, incrementCompletedSentences, resetProgress } = useStore();
  const [currentSentenceId, setCurrentSentenceId] = useState<string | null>(null);
  const [mounted, setMounted] = useState(false);

  // We use useEffect to avoid hydration mismatch with localStorage
  useEffect(() => {
    setMounted(true);
    setCurrentSentenceId(getNextSentenceId());
  }, [getNextSentenceId]);

  if (!mounted || !currentSentenceId) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center">
        <div className="animate-pulse flex flex-col items-center">
          <div className="h-8 w-8 bg-blue-400 rounded-full mb-4"></div>
          <div className="text-gray-400 font-medium">Loading practice...</div>
        </div>
      </div>
    );
  }

  const currentSentence = sentences.find(s => s.id === currentSentenceId) || sentences[0];

  const handleNext = () => {
    incrementCompletedSentences();
    setCurrentSentenceId(getNextSentenceId(currentSentenceId));
  };

  return (
    <div className="min-h-screen flex flex-col items-center py-12 px-4 font-sans">
      
      <div className="w-full max-w-2xl mb-8 flex justify-between items-center">
        <h1 className="text-3xl font-extrabold flex items-center gap-3 text-transparent bg-clip-text bg-gradient-to-r from-blue-600 to-cyan-500 dark:from-blue-400 dark:to-cyan-300 drop-shadow-sm tracking-tight">
          <BookOpen className="text-blue-600 dark:text-blue-400 w-8 h-8 drop-shadow-md" />
          DeutschDive
        </h1>
        
        <div className="flex items-center gap-4">
          <select 
            className="text-sm bg-white dark:bg-gray-800 border border-gray-300 dark:border-gray-700 rounded-md py-1 px-2 shadow-sm focus:outline-none focus:ring-2 focus:ring-blue-500 text-gray-900 dark:text-gray-100"
            value={selectedLevel}
            onChange={(e) => {
              const level = e.target.value as any;
              setSelectedLevel(level);
              setCurrentSentenceId(getNextSentenceId(currentSentenceId));
            }}
          >
            <option value="All">All Levels</option>
            <option value="A1.1">Easy</option>
            <option value="A1.2">Medium</option>
            <option value="A2">Hard</option>
            <option value="B1+">Expert</option>
          </select>

          <div className="text-sm text-gray-500 dark:text-gray-400 bg-white dark:bg-gray-800 px-3 py-1 rounded-full shadow-sm border border-gray-100 dark:border-gray-700 flex items-center gap-3">
            <span>Completed: <span className="font-bold text-blue-600 dark:text-blue-400">{completedSentences}</span></span>
            <span className="w-px h-4 bg-gray-200 dark:bg-gray-700"></span>
            <span>Missed: <span className="font-bold text-red-500 dark:text-red-400">{Object.keys(missedWords).length}</span></span>
          </div>
          
          <button 
            onClick={() => {
              if (confirm("Are you sure you want to reset your progress?")) {
                resetProgress();
              }
            }}
            className="text-xs text-gray-500 dark:text-gray-400 hover:text-red-600 dark:hover:text-red-400 hover:bg-red-50 dark:hover:bg-red-900/30 px-2 py-1 rounded transition-colors"
          >
            Reset
          </button>
          
          <ThemeToggle />
        </div>
      </div>

      <Flashcard 
        key={currentSentence.id} 
        sentence={currentSentence} 
        onNext={handleNext} 
      />

      <div className="mt-12 text-center flex items-center justify-center gap-2 text-xs text-gray-400 dark:text-gray-500 w-full max-w-xl">
        <AlertTriangle className="w-4 h-4 flex-shrink-0" />
        <p>
          Some content (such as sentence blanks, hints, and questions) is generated by an AI and may occasionally contain inaccuracies.
        </p>
      </div>
    </div>
  );
}
